task_name: "distinguish_add_base_2"
input: "/home/lkh/siga/dataset/ABC/shape_feats/processed/new/v3/filter_face_area/1/filtered.jsonl"
output_dir: "/home/lkh/siga/dataset/ABC/shape_feats/processed/new/v3/distinguish_add_base/2"
classify_name: 
  - add
  - base
