task_name: "distinguish_unvalid_all_2"
task: "record_unvalid"
txt_name_list: '/home/lkh/siga/CADIMG/dataset/process/ABC/rewrite_unvalid/src/unvalid_base_add_far1.txt'
txt_output_paths:
  output_txt_inter:  '/home/lkh/siga/CADIMG/dataset/process/ABC/rewrite_unvalid/src/unvalid_base_add_inter3.txt'
  output_txt_far: '/home/lkh/siga/CADIMG/dataset/process/ABC/rewrite_unvalid/src/unvalid_base_add_far3.txt'
  output_txt_error: '/home/lkh/siga/CADIMG/dataset/process/ABC/rewrite_unvalid/src/unvalid_base_add_error3.txt'
